export const MEDIA_SET_URL = "MEDIA_SET_URL";
export const MEDIA_UPLOAD_START = "MEDIA_UPLOAD_START";
export const MEDIA_UPLOAD_COMPLETE = "MEDIA_UPLOAD_COMPLETE";

export const IMAGE_SCAN_START = "IMAGE_SCAN_START"
export const IMAGE_SCAN_COMPLETE = "IMAGE_SCAN_COMPLETE"

export const VIDEO_SCAN_START = "VIDEO_SCAN_START"
export const VIDEO_SCAN_COMPLETE = "VIDEO_SCAN_COMPLETE"