export const MEDIA_SET_URL = "MEDIA_SET_URL";
export const MEDIA_UPLOAD_START = "MEDIA_UPLOAD_START";
export const MEDIA_UPLOAD_COMPLETE = "MEDIA_UPLOAD_COMPLETE";
export const MEDIA_SCAN_START = "MEDIA_SCAN_START"
export const MEDIA_SCAN_COMPLETE = "MEDIA_SCAN_COMPLETE"