export const IMAGE_SET_URL = "IMAGE_SET_URL";
export const IMAGE_UPLOAD_START = "IMAGE_UPLOAD_START";
export const IMAGE_UPLOAD_COMPLETE = "IMAGE_UPLOAD_COMPLETE";
export const IMAGE_SCAN_START = "IMAGE_SCAN_START"
export const IMAGE_SCAN_COMPLETE = "IMAGE_SCAN_COMPLETE"