// ACTIONS
export const TO_MEDIA_PLAYER = "TO_MEDIA_PLAYER";
export const TO_MEDIA_SELECTION = "TO_MEDIA_SELECTION";

// APP STATES
export const MEDIA_SELECTION = "MEDIA_SELECTION";
export const MEDIA_PLAYER = "MEDIA_PLAYER";
