export const SOUND_SET_SOUNDLIST = "SOUND_SET_SOUNDLIST";
export const SOUNDS_CLEAR_ALL = "SOUNDS_CLEAR_ALL";

export const SOUND_GET = "SOUND_GET";
export const SOUND_GET_SUCCESS = "SOUND_GET_SUCCESS";
export const SOUND_GET_ERROR = "SOUND_GET_ERROR";

export const SOUND_DELETE = "SOUND_DELETE";
export const SOUND_PLAY = "SOUND_PLAY";
export const SOUND_STOP = "SOUND_STOP";

export const SOUNDS_PLAY_ALL = "SOUNDS_PLAY_ALL";
export const SOUNDS_STOP_ALL = "SOUNDS_STOP_ALL";
