#!/bin/bash
cd /home/ec2-user/node-website
curl -sL https://rpm.nodesource.com/setup | bash -
yum install -y nodejs

cd /home/ec2-user/python-flask-service/src/frontend
npm install
npm run build

easy_install pip
pip install virtualenv
cd /home/ec2-user/python-flask-service
virtualenv environment
source environment/bin/activate
pip install -r requirements.txt
pip install supervisor
