#!/bin/bash
cd /home/ec2-user/python-flask-service
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash
. ~/.nvm/nvm.sh
nvm install 8.9.1
node -e "console.log('Running Node.js ' + process.version)"

cd /home/ec2-user/python-flask-service/frontend
npm install
npm run build

easy_install pip
pip install virtualenv
cd /home/ec2-user/python-flask-service
virtualenv environment
source environment/bin/activate
pip install -r requirements.txt
pip install supervisor
